/* User: admin, Password: supperpassword*/
INSERT INTO PUBLIC.APPLICATION_USER (ID, E_ROLE, PASSWORD, USERNAME, ACTIVE)
VALUES (1, 2, '$2a$10$kl4mzDxIFSRNtV2Kloxpo.XHxjNak5oKneAF7BqGDkljlsrdJjA2C', 'admin', true);

INSERT INTO PUBLIC.CATEGORIES (ID, APPLICATION_USER_ID, DESCRIPTION, E_ICON, NAME)
VALUES (1, 1, 'test', null, '1test');

INSERT INTO PUBLIC.PLACE (ID, E_ICON, NAME, APPLICATION_USER_ID)
VALUES (1, null, 'test', 1);

INSERT INTO PUBLIC.ENTRY (ID, APPLICATION_USER_ID, CHECK_IN, CHECK_OUT, CATEGORIE_ID, PLACE_ID)
VALUES (1, 1, '2021-09-28 15:17:24.000000', '2021-09-29 15:17:26.000000', 1, 1);